project_id = "wwgzxhmxdquzgzdofysx"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 17

[auth]
enabled = true
site_url = "https://cliente-avanco-app.vercel.app"
additional_redirect_urls = ["http://localhost:5173"]

[auth.email]
enable_signup = true
enable_confirmations = true
double_confirm_changes = true
max_frequency = "1m"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true
file_size_limit = "24MiB"
